dist: trusty
language: java
# use Java 8
jdk:
- oraclejdk8

services:
- rabbitmq

before_script:
- sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass '?_TK$czHb9LhyWy8W2G4gZAa@byj8H&4'

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

notifications:
  emails:
    recipients:  
    - ashzhouyue@gmail.com
    on_success: always  
    on_failure: always