server:
  port: 8090
  servlet:
    context-path: /api

stripe:
  api:
    key: sk_test_NtqJqdbiZnwPNxKVieFNHcB1

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
  file: app.log


spring:
  profiles:
    active: "dev"
#    active: "prod"