server:
  port: 8080
  #  servlet:
  #    context-path: /api
  shutdown: graceful
#  servlet:
#    context-path: /context-path


stripe:
  api:
    key: sk_test_NtqJqdbiZnwPNxKVieFNHcB1

logging:
  level:
    #    ROOT: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.jz.nebula: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#  file:
#    name: app.log

spring:
  profiles:
    active: "dev"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#    active: "prod"
