server:
  port: 8090
  servlet:
    context-path: /api

stripe:
  api:
    key: sk_test_NtqJqdbiZnwPNxKVieFNHcB1


spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 923ffa154e8a81
    password: 37cad321d4ea2c
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    default-property-inclusion: non_empty

  redis:
    cluster:
      nodes:
    #      Ensue in AWS enable the cluster feature
    #      nodes: nebula-redis-1.2g0kc4.0001.apse2.cache.amazonaws.com:6379

    #    host: iresdev1.intsrv.net
    host: localhost
    #    host: nebula-redis-1.2g0kc4.0001.apse2.cache.amazonaws.com
    port: 6379
    password: ?_TK$czHb9LhyWy8W2G4gZAa@byj8H&4
    #    password: ?_TK$czHb9LhyWy8W2G4gZAabyj8H&4
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0

  management:
    health:
      redis:
        enabled: false

  datasource:
    #    url: jdbc:postgresql://elebufffalo-nebula-spring.cdtaauatufxe.ap-southeast-2.rds.amazonaws.com:5432/nebula_spring
    url: jdbc:postgresql://localhost:5432/nebula_spring
    username: postgres
    password: postgres
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    driver-class-name: org.postgresql.Driver


  jpa:
    openInView: false
    show_sql: true
    #    generate-ddl: true
    #    hibernate:
    #      ddl-auto: create
    #      ddl-auto: create-drop
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true

